{% set name = "spatialdata-io" %}
{% set version = "0.7.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spatialdata_io-{{ version }}.tar.gz
  sha256: 4754365b7bc8e1db297ee0c63c41c88ce98062398234e8bcc5e6382754e9afbc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - anndata
    - dask
    - click
    - dask-image
    - h5py
    - imagecodecs
    - joblib
    - numpy
    - pyarrow
    - python >={{ python_min }}
    - readfcs
    - scanpy
    - scikit-image
    - spatialdata >=0.7.3a0
    - tifffile >=2023.8.12
    - ome-types
    - xmltodict
test:
  imports:
    - spatialdata_io
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scverse/spatialdata-io
  summary: SpatialData IO for common techs
  dev_url: https://github.com/scverse/spatialdata-io
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - LucaMarconato
    - giovp
    - melonora
    - kevinyamauchi
